--USUARIOS
CREATE TABLE USUARIOS
(
  LOGIN       VARCHAR(20) PRIMARY KEY,
  NOME        VARCHAR(50) NOT NULL,
  SENHA       VARCHAR(10),
  SN_ATIVO    VARCHAR(1)
);

--USUARIOS_CONFIG
CREATE TABLE USUARIOS_CONFIG
(
  LOGIN       		VARCHAR(20),  
  PLANO_DE_FUNDO       	VARCHAR(1),
  DS_CONFIG   		VARCHAR(100),
  VALOR       		VARCHAR(100),
  TIPO_CONFIG		VARCHAR(100)
);

ALTER TABLE USUARIOS_CONFIG ADD CONSTRAINT PK_USUARIOS_CONFIG PRIMARY KEY (LOGIN, TIPO_CONFIG);
ALTER TABLE USUARIOS_CONFIG ADD CONSTRAINT FK_USUARIOS_CONFIGUSUARIOS FOREIGN KEY (LOGIN) REFERENCES USUARIOS (LOGIN);

--CLIENTES
CREATE TABLE CLIENTES
(
  COD_CLIENTE INTEGER    PRIMARY KEY,
  NOME        VARCHAR(50) NOT NULL,
  CPF         VARCHAR(14) NOT NULL,
  DATA_NASC   DATE,
  ENDERECO    VARCHAR(80),
  BAIRRO      VARCHAR(50),
  CEP         VARCHAR(10),
  CIDADE      VARCHAR(50),
  ESTADO      VARCHAR(2),
  FONE1       VARCHAR(14),
  FONE2       VARCHAR(14),
  SEXO        VARCHAR(1),
  RESTRICAO   VARCHAR(1)
);

--MARCAS
CREATE TABLE MARCAS
(
  COD_MARCA   INTEGER    PRIMARY KEY,
  DS_MARCA    VARCHAR(30) NOT NULL
);

--MODELOS
CREATE TABLE MODELOS
(
  COD_MARCA   INTEGER, 
  COD_MODELO  INTEGER, 
  DS_MODELO   VARCHAR(30) NOT NULL
);

ALTER TABLE MODELOS ADD CONSTRAINT PK_MODELOS PRIMARY KEY (COD_MARCA, COD_MODELO);
ALTER TABLE MODELOS ADD CONSTRAINT FK_MODELOSMARCAS FOREIGN KEY (COD_MARCA) REFERENCES MARCAS (COD_MARCA);

--MOV_VEICULOS
CREATE TABLE MOV_VEICULOS
(
  COD_MOV_VEICULOS    INTEGER PRIMARY KEY,
  COD_MARCA           INTEGER,
  COD_MODELO          INTEGER,
  VERSAO              VARCHAR(20),
  ANO_FABRICACAO      INTEGER,
  ANO_MODELO          INTEGER,
  COR                 VARCHAR(20),
  PLACA               VARCHAR(8),
  RENAVAM             VARCHAR(10),
  OBSERVACOES         VARCHAR(500),
  VALOR_ENTRADA       NUMERIC(10,2),
  VALOR_SAIDA         NUMERIC(10,2),  
  DATA_ENTRADA        DATE,
  DATA_SAIDA          DATE,  
  COD_CLIENTE_ENTRADA INTEGER,  
  COD_CLIENTE_SAIDA   INTEGER  
);  

ALTER TABLE MOV_VEICULOS ADD CONSTRAINT FK_MOV_VEICULOSMODELOS   FOREIGN KEY (COD_MARCA, COD_MODELO) REFERENCES MODELOS (COD_MARCA, COD_MODELO);
ALTER TABLE MOV_VEICULOS ADD CONSTRAINT FK_MOV_VEICULOSCLIENTES1 FOREIGN KEY (COD_CLIENTE_ENTRADA)   REFERENCES CLIENTES (COD_CLIENTE);
ALTER TABLE MOV_VEICULOS ADD CONSTRAINT FK_MOV_VEICULOSCLIENTES2 FOREIGN KEY (COD_CLIENTE_SAIDA)     REFERENCES CLIENTES (COD_CLIENTE);

INSERT INTO USUARIOS VALUES ('ADMIN','Administrador','123','S');
COMMIT;



 
